context:
  version: 5.1.0

package:
  name: jolt-physics
  version: ${{ version }}

source:
  url: https://github.com/jrouwe/JoltPhysics/archive/refs/tags/v${{ version }}.zip
  sha256: 10fcc863ae2b9d48c2f22d8b0204034820e57a55f858b7c388ac9579d8cf4095

requirements: 
  build: 
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}

build:
  number: 0

about:
  homepage: https://github.com/jrouwe/JoltPhysics
  license: MIT
  license_file: LICENSE
  summary: A multi core friendly rigid body physics and collision detection library.
  description: A multi core friendly rigid body physics and collision detection library. Written in C++. Suitable for games and VR applications. Used by Horizon Forbidden West. 
  documentation: https://jrouwe.github.io/JoltPhysics/
  repository: https://github.com/jrouwe/JoltPhysics

extra:
  recipe-maintainers:
    - baszalmstra
