context:
  version: "5.6.0"
  build_number: 1

package:
  name: jolt-physics
  version: ${{ version }}

source:
  url: https://github.com/jrouwe/JoltPhysics/archive/refs/tags/v${{ version }}.zip
  sha256: 0af9beea51637ef805e624fe838ea2870f7b68cd48cbe1615c853bd9bcf4f1d7

build:
  number: ${{ build_number + 100 * (microarch_level|default(1)|int - 1) }}
  variant:
    use_keys:
      - microarch_level
  script:
    interpreter: brush
    env:
      JOLT_X86_SIMD: ${{ "ON" if microarch_level|default(1)|int >= 3 else "OFF" }}
    content: |
      set -eux

      # AVX512 requires microarchitecture level 4, which conda-forge CI cannot guarantee.
      cmake -S "$SRC_DIR/Build" -B build -G Ninja \
          ${CMAKE_ARGS} \
          -DCMAKE_INSTALL_PREFIX="${LIBRARY_PREFIX:-$PREFIX}" \
          -DBUILD_SHARED_LIBS=ON \
          -DCMAKE_BUILD_TYPE=Distribution \
          -DCROSS_PLATFORM_DETERMINISTIC=ON \
          -DUSE_SSE4_1=$JOLT_X86_SIMD \
          -DUSE_SSE4_2=$JOLT_X86_SIMD \
          -DUSE_AVX=$JOLT_X86_SIMD \
          -DUSE_AVX2=$JOLT_X86_SIMD \
          -DUSE_AVX512=OFF \
          -DUSE_LZCNT=$JOLT_X86_SIMD \
          -DUSE_TZCNT=$JOLT_X86_SIMD \
          -DUSE_F16C=$JOLT_X86_SIMD \
          -DUSE_FMADD=OFF \
          -DJPH_USE_CPU_COMPUTE=ON \
          -DJPH_USE_DX12=OFF \
          -DJPH_USE_MTL=OFF \
          -DJPH_USE_VK=OFF \
          -DTARGET_VIEWER=OFF \
          -DTARGET_SAMPLES=OFF \
          -DTARGET_HELLO_WORLD=OFF \
          -DTARGET_UNIT_TESTS=OFF \
          -DTARGET_PERFORMANCE_TEST=OFF
      cmake --build build --target install

requirements:
  build:
    - if: unix and x86_64
      then: x86_64-microarch-level ==${{ microarch_level }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
    - brush

tests:
  - package_contents:
      include:
        - Jolt/Jolt.h
      lib:
        - Jolt

about:
  homepage: https://github.com/jrouwe/JoltPhysics
  license: MIT
  license_file: LICENSE
  summary: A multi core friendly rigid body physics and collision detection library.
  description: A multi core friendly rigid body physics and collision detection library. Written in C++. Suitable for games and VR applications. Used by Horizon Forbidden West.
  documentation: https://jrouwe.github.io/JoltPhysics/
  repository: https://github.com/jrouwe/JoltPhysics

extra:
  recipe-maintainers:
    - baszalmstra
