conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
remote_ci_setup:
- conda-forge-ci-setup=4
- rattler-build>=1
